
const CONFIG = {
    BACKEND_URL: 'http://localhost:8080',  // CHANGE THIS TO YOUR NGROK URL
    STREAM_ENDPOINT: '/stream',
    HEALTH_ENDPOINT: '/health',
    RECONNECT_DELAY: 3000,
    MAX_RECONNECT_ATTEMPTS: 5
};
